FROM apache/spark-py:v3.4.0

USER root

WORKDIR /opt/spark/work

COPY spark/jobs/wordcount.py /opt/spark/work/wordcount.py
COPY spark/jobs/analysis.py /opt/spark/work/analysis.py
COPY spark/jobs/sample.txt /opt/spark/work/sample.txt

RUN chown -R 185:0 /opt/spark/work && chmod -R 775 /opt/spark/work

USER 185
