apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-douban-a3-exec1
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: swr.cn-north-4.myhuaweicloud.com/swjtu2551/pyspark-douban:3.4
  imagePullPolicy: Always
  imagePullSecrets:
    - swr-secret
  mainApplicationFile: local:///opt/spark/work/douban_a3_pyspark.py
  sparkVersion: "3.4.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark
    env:
      - name: A3_EXECUTORS
        value: "1"
  executor:
    cores: 1
    instances: 1
    memory: "1g"
