apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  APP_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default
type: Opaque
data:
  password: UmVkaXNAMTIzNDU2
