apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: default
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: '{
      "type": "public",
      "bandwidth_name": "cce-course-design-backend",
      "bandwidth_chargemode": "traffic",
      "bandwidth_size": 1,
      "bandwidth_sharetype": "PER",
      "eip_type": "5_bgp",
      "name": "cce-course-design-backend"
    }'
    kubernetes.io/elb.enterpriseID: "0"
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: service0
      port: 80
      protocol: TCP
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
