apiVersion: v1
kind: Service
metadata:
  name: mnist-ddp-master
  namespace: default
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: mnist-ddp
    batch.kubernetes.io/job-completion-index: "0"
  ports:
    - name: ddp
      port: 29500
      targetPort: 29500
